project:
  type: book
  output-dir: ../docs  # Uncomment if you want to specify output directory

book:
  page-navigation: true
  back-to-top-navigation: true
  #title: "Complex Disordered Matter"
  sidebar:
    smooth-scroll: true
    logo: courselogo.png
    style: "docked"
    search: true
    collapse-level: 1
  chapters:
    - href: index.qmd
      text: Overview  
    - href: reading.qmd
      text: "Recommended texts"
    - part: "Unifying concepts"
      chapters:
         - text: "Introduction to phase behaviour"
           href:  phase-transitions/introduction.qmd
         - text: "Background concepts"
           href: phase-transitions/background.qmd
         - text: "The approach to criticality"
           href:  phase-transitions/approach-to-criticality.qmd
         - text: "The Ising model"
           href: phase-transitions/Ising-model.qmd            
         - text: "Mean field theory"
           href:  phase-transitions/mean-field-theory.qmd
          #  keep commented
#        - text: "The lattice gas"
#           href: phase-transitions/lattice-gas.qmd
# end of kee commented

         - text: "The static scaling hypothesis"
           href: phase-transitions/scaling.qmd
         - text: "Universality and renormalization group theory"
           href:  phase-transitions/rg.qmd
        #   - text: "RG- the effective coupling viewpoint"
        #     href: phase-transitions/rg-effective-coupling.qmd 
         - text: "Introduction to stochastic processes"  
           href: phase-transitions/master-equation-and-diffusion.qmd
         - text: "Langevin and Brownian dynamics"
           href: phase-transitions/Brownian-and-Langevin-dynamics.qmd
         - text: "Nucleation, growth and spinodal decomposition"
           href: phase-transitions/nucleation-and-growth.qmd 
        #   - text: "Dynamics of fluctuations (non-examinable)"
        #    href: phase-transitions/dynamics-of-fluctuations.qmd  
         - text: "Precourse reading and revision"
           href: phase-transitions/precourse-reading.qmd
         - text: "Problems" 
           href: phase-transitions/problems.qmd
         - text: "Lecture slides" 
           href: phase-transitions/Lecture Slides/Slides.pdf

         - text: "Solutions to problems"
           href: phase-transitions/Solutions_partial.qmd    
   #      - text: "Preparation for first coursework assignment"
   #        href: phase-transitions/assignment_prep.qmd      
         - text: "First coursework assignment"     
           href: phase-transitions/assignment_October2025.qmd                    
#          - href: phase-transitions/live-test.qmd
#            text: "Coding"  
    - part: "First experimental interlude"
      chapters:
        - href: experimental/part1.ipynb
          text: "Macroscopic measurements"
        - href: experimental/part2.ipynb
          text: "Real-space measurements"

    - part: "Complex disordered systems"
      chapters:
        - href: soft-matter/soft-matter_intro.qmd
          text: "Entropy matters"
        - href: soft-matter/soft-matter_colloids.qmd
          text: "Colloids"
    #     - href: soft-matter/soft-matter_polymers.qmd
    #       text: "Polymers"
    #     - href: soft-matter/soft-matter_liquidcrystals.qmd
    #       text: "Liquid crystals"
    #     - href: soft-matter/soft-matter_surfactants.qmd
    #       text: "Surfactants"
    #     - href: soft-matter/soft-matter_glasses.qmd
    #       text: "Arrested states"
    #     - href: soft-matter/soft-matter_active.qmd
    #       text: "Active matter"
    #     # - href: soft-matter/soft-matter_readings.qmd
    #       # text: "Readings"
        - href: soft-matter/soft-matter_problems.qmd
          text: "Problems"
    - text: "Notes as pdf" 
      href: notes.pdf
  # appendices:
  #   - href: revision_guide.qmd
  #     text: "Revision guide"
  #   - href: phase-transitions/concepts_map.qmd
  #     text: "Concept maps"    
format:
  live-html:
    theme: cosmo
    page-layout: full
    grid:
      sidebar-width: 305px  
      body-width: 1000px
    toc: true
    mainfont: sans-serif
    fontsize: 15px
    pyodide:
        cell-options:
          autorun: true

  # pdf:
  #    documentclass: report
  #    classoption: [enabledeprecatedfontcommands]
  #    # papersize: a4paper
  #    mainfont: "Helvetica" 
  #    bibliography:
  #      - soft-matter/references.bib
  #    geometry:
  #      - top=2cm
  #      - left=2cm
  #      - right=5cm
  #    execute:
  #      echo: false      # donâ€™t show code
  #      warning: false
  #      error: false
  #      eval: false      # completely skip execution